import { NavLinks } from "./ui/nav-links" 
export const metadata = {
  title: 'radish ~ app',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <NavLinks />
        <main>{children}</main>
      </body>
    </html>
  )
}
